// ponytail: generate styled HTML for download — users open in browser → print to PDF
// No external deps. Embedded CSS. Print-friendly.

const CSS = `
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; color: #1a1a1a; line-height: 1.6; padding: 40px; max-width: 900px; margin: 0 auto; }
  h1 { font-size: 22px; margin-bottom: 4px; }
  h2 { font-size: 16px; margin: 20px 0 8px; color: #444; }
  h3 { font-size: 14px; margin-bottom: 4px; }
  .header { text-align: center; margin-bottom: 24px; border-bottom: 2px solid #1a1a1a; padding-bottom: 16px; }
  .header .brand { font-size: 24px; font-weight: 700; letter-spacing: 1px; }
  .header .sub { font-size: 12px; color: #888; margin-top: 2px; }
  .meta { display: flex; justify-content: space-between; font-size: 12px; color: #666; margin-bottom: 20px; }
  .card { border: 1px solid #e0e0e0; border-radius: 8px; padding: 20px; margin-bottom: 16px; page-break-inside: avoid; }
  .card h3 { font-size: 13px; color: #888; text-transform: uppercase; letter-spacing: 0.5px; margin-bottom: 8px; }
  .card .subject { font-size: 16px; font-weight: 600; margin-bottom: 12px; }
  .card .body { font-size: 13px; white-space: pre-wrap; margin-bottom: 12px; }
  .card .translation { font-size: 13px; color: #555; border-top: 1px dashed #ddd; padding-top: 10px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; font-size: 13px; }
  th, td { border: 1px solid #ddd; padding: 8px 10px; text-align: left; }
  th { background: #f5f5f5; font-weight: 600; }
  td.num, th.num { text-align: right; }
  .total-row td { font-weight: 600; background: #fafafa; }
  .two-col { display: flex; gap: 24px; margin: 12px 0; }
  .two-col > div { flex: 1; }
  .badge { display: inline-block; background: #f0f0f0; padding: 2px 8px; border-radius: 4px; font-size: 11px; margin: 2px; }
  .spec-grid { display: flex; flex-wrap: wrap; gap: 4px 0; }
  .spec-item { width: 50%; font-size: 13px; padding: 4px 0; border-bottom: 1px solid #f0f0f0; }
  .spec-item .label { color: #888; }
  .spec-item .val { font-weight: 500; }
  ul { padding-left: 18px; font-size: 13px; color: #555; }
  ul li { margin-bottom: 2px; }
  .zh-block { background: #f8f8f8; border-radius: 6px; padding: 16px; margin-top: 20px; }
  .zh-block h2 { margin-top: 0; }
  .zh-block .spec-item { border-color: #e8e8e8; }
  .obj-block { margin-bottom: 12px; page-break-inside: avoid; }
  .obj-block .q { font-size: 13px; font-weight: 600; color: #c0392b; margin-bottom: 4px; }
  .obj-block .a { font-size: 13px; color: #555; padding-left: 12px; }
  .footer-note { font-size: 11px; color: #aaa; text-align: center; margin-top: 30px; padding-top: 12px; border-top: 1px solid #eee; }
  @media print { body { padding: 20px; } }
</style>`;

function head(title: string) {
  return `<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8"><title>${title}</title>${CSS}</head><body>`;
}

function foot() {
  return `<div class="footer-note">Generated by TradePilot — AI Co-pilot for Global Trade</div></body></html>`;
}

function d(n: number) { return n.toFixed(2); }

// --- Mail ---
export function exportMailHTML(data: any): void {
  const emails = data.results || data;
  const html = head('ColdMail — 开发信') +
    `<div class="header"><div class="brand">TradePilot</div><div class="sub">ColdMail · AI 开发信工厂</div></div>` +
    emails.map((r: any, i: number) =>
      `<div class="card">
        <h3>策略 ${i + 1} · ${r.strategy} <span style="font-weight:400;color:#aaa;font-size:11px">${r.strategy_en}</span></h3>
        <div class="subject">${esc(r.subject)}</div>
        <div class="body">${esc(r.body)}</div>
        ${r.translation ? `<div class="translation"><strong>中文翻译：</strong><br>${esc(r.translation)}</div>` : ''}
      </div>`
    ).join('\n') + foot();
  downloadHTML(html, `coldmail-${ts()}.html`);
}

// --- Catalog ---
export function exportCatalogHTML(data: any): void {
  const r = data.results || data;
  const html = head('CatalogX — 产品目录') +
    `<div class="header"><div class="brand">TradePilot</div><div class="sub">CatalogX · AI 产品目录生成器</div></div>` +
    `<h1>${esc(r.title)}</h1><p style="color:#666;font-size:14px;margin-bottom:16px">${esc(r.overview)}</p>` +
    `<h2>Specifications</h2><div class="spec-grid">` +
    (r.specs || []).map((s: any) => `<div class="spec-item"><span class="label">${esc(s.label)}</span> <span class="val">${esc(s.value)}</span></div>`).join('') +
    `</div><h2>Features & Benefits</h2><ul>` +
    (r.features || []).map((f: string) => `<li>${esc(f)}</li>`).join('') +
    `</ul><p style="font-size:13px;color:#555;margin:12px 0">${esc(r.factory_note || '')}</p>` +
    `<p style="font-weight:600;font-size:14px">${esc(r.cta || '')}</p>` +
    (r.zh ? `<div class="zh-block">
      <h2>中文参考</h2><h1 style="font-size:18px">${esc(r.zh.title_cn)}</h1>
      <p style="color:#666;font-size:14px;margin-bottom:12px">${esc(r.zh.overview_cn)}</p>
      <div class="spec-grid">${(r.zh.specs_cn || []).map((s: any) => `<div class="spec-item"><span class="label">${esc(s.label_cn)}</span> <span class="val">${esc(s.value_cn)}</span></div>`).join('')}</div>
      <h2>产品特性</h2><ul>${(r.zh.features_cn || []).map((f: string) => `<li>${esc(f)}</li>`).join('')}</ul>
      <p style="font-size:13px;color:#555">${esc(r.zh.factory_note_cn || '')}</p>
      <p style="font-weight:600;font-size:14px">${esc(r.zh.cta_cn || '')}</p>
    </div>` : '') + foot();
  downloadHTML(html, `catalogx-${ts()}.html`);
}

// --- PI / Quote ---
export function exportQuoteHTML(data: any): void {
  const r = data.results || data;
  const items = (r.items || []).map((i: any) =>
    `<tr><td>${i.no}</td><td>${esc(i.description)}</td><td class="num">${i.qty}</td><td>${esc(i.unit)}</td><td class="num">$${d(i.unit_price)}</td><td class="num">$${d(i.amount)}</td></tr>`
  ).join('');
  const html = head('PI Pilot — 报价单') +
    `<div class="header"><div class="brand">PROFORMA INVOICE</div><div class="sub">TradePilot · AI 报价单 & PI 生成器</div></div>` +
    `<div class="meta"><span>PI No: <strong>${esc(r.quote_no)}</strong></span><span>Date: <strong>${esc(r.date)}</strong></span></div>` +
    `<div class="two-col">
      <div><h3>Seller</h3><p style="font-size:13px;font-weight:600">${esc(r.seller?.name || '')}</p><p style="font-size:12px;color:#666;white-space:pre-wrap">${esc(r.seller?.address || '')}</p></div>
      <div><h3>Buyer</h3><p style="font-size:13px;font-weight:600">${esc(r.buyer?.name || '')}</p><p style="font-size:12px;color:#666;white-space:pre-wrap">${esc(r.buyer?.address || '')}</p></div>
    </div>` +
    `<table><thead><tr><th>No</th><th>Description</th><th class="num">Qty</th><th>Unit</th><th class="num">Unit Price</th><th class="num">Amount</th></tr></thead><tbody>${items}</tbody></table>` +
    `<div style="display:flex;justify-content:flex-end"><table style="width:280px">
      <tr><td>Subtotal</td><td class="num">$${d(r.subtotal || 0)}</td></tr>
      <tr><td>Shipping</td><td class="num">${esc(r.shipping || 'TBD')}</td></tr>
      <tr class="total-row"><td>Total</td><td class="num">$${d(r.total || 0)}</td></tr>
    </table></div>` +
    `<table style="margin-top:16px">
      <tr><td style="width:140px;color:#888">Incoterms</td><td><strong>${esc(r.incoterms || '')}</strong></td></tr>
      <tr><td style="color:#888">Payment Terms</td><td>${esc(r.payment_terms || '')}</td></tr>
      <tr><td style="color:#888">Delivery</td><td>${esc(r.delivery || '')}</td></tr>
      <tr><td style="color:#888">Validity</td><td>${esc(r.validity || '')}</td></tr>
    </table>` +
    (r.notes ? `<p style="font-size:12px;color:#888;margin-top:12px">${esc(r.notes)}</p>` : '') +
    `<p style="font-size:11px;color:#aaa;margin-top:20px">This is a computer-generated document. For any questions, please contact the seller directly.</p>` +
    foot();
  downloadHTML(html, `pi-${esc(r.quote_no || ts())}.html`);
}

// --- Expo ---
export function exportExpoHTML(data: any): void {
  const r = data.results || data;
  const pc = r.product_card || {};
  const tp = r.talking_points || {};
  const oh = r.objection_handlers || [];
  const html = head('ExpoKit — 展会话术') +
    `<div class="header"><div class="brand">ExpoKit</div><div class="sub">TradePilot · AI 展会急救包</div></div>` +
    `<h1>${esc(pc.title || '')}</h1><p style="color:#666;font-size:14px">${esc(pc.tagline || '')}</p>` +
    `<h2>Key Specs</h2><div>${(pc.key_specs || []).map((s: string) => `<span class="badge">${esc(s)}</span>`).join(' ')}</div>` +
    `<h2>USPs</h2><ul>${(pc.usp || []).map((s: string) => `<li>${esc(s)}</li>`).join('')}</ul>` +
    `<h2>Pricing</h2><table><tr><td style="color:#888;width:160px">FOB Price</td><td><strong>${esc(r.pricing?.fob_price || 'N/A')}</strong></td></tr>
    <tr><td style="color:#888">MOQ</td><td>${esc(r.pricing?.moq || 'N/A')}</td></tr>
    <tr><td style="color:#888">Sample Lead Time</td><td>${esc(r.pricing?.sample_lead_time || 'N/A')}</td></tr>
    <tr><td style="color:#888">Bulk Lead Time</td><td>${esc(r.pricing?.bulk_lead_time || 'N/A')}</td></tr></table>` +
    `<h2>Talking Points</h2><div class="two-col">
      <div><h3 style="font-size:12px;color:#888;margin-bottom:4px">ENGLISH</h3><ul>${(tp.en || []).map((s: string) => `<li>${esc(s)}</li>`).join('')}</ul></div>
      <div><h3 style="font-size:12px;color:#888;margin-bottom:4px">中文</h3><ul>${(tp.zh || []).map((s: string) => `<li>${esc(s)}</li>`).join('')}</ul></div>
    </div>` +
    `<h2>Objection Handlers</h2>` +
    oh.map((o: any) => `<div class="obj-block"><div class="q">❓ ${esc(o.if_buyer_says)}</div><div class="a">✅ ${esc(o.you_respond)}</div></div>`).join('') +
    foot();
  downloadHTML(html, `expokit-${ts()}.html`);
}

// --- helpers ---
function esc(s: string): string {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function downloadHTML(html: string, filename: string) {
  const blob = new Blob([html], { type: 'text/html;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  a.click();
  URL.revokeObjectURL(url);
}

function ts(): string { return Date.now().toString(36); }
